### ISSUE TITLE
Problem on time.clock() method with Python 3.8

### ISSUE THREAD

**Issue by Monrillo** [ymbahe/hydrangea#1]
I had this issue using ReadRegion method :

> 
> `----> 1 gas2 = hy.ReadRegion(snapshot_file, 0, subhalo_0.Coordinates, 0.1, exact=True)
> 
> ~/.local/lib/python3.8/site-packages/hydrangea/read_region.py in __init__(self, file_name, part_type, anchor, size, shape, anchor_style, verbose, exact, units, coordinate_units, read_units, map_file, periodic, load_full, join_threshold, bridge_threshold, bridge_gap)
>     130                  bridge_gap=0.5):
>     131 
> --> 132         stime = time.clock()
>     133 
>     134         # Store 'simple' parameters in internal variables
> 
> AttributeError: module 'time' has no attribute 'clock'`

A research on Google explains that this function has been deprecated and has been removed on Python 3.8.

**Comment by ymbahe** [comment]
Thanks @Monrillo! I could have sworn that I had replaced all the time.clock() calls, but apparently not that one. Should be fixed now.
